//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreByVlasovAndry.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int id_deal { get; set; }
        public int user_id { get; set; }
        public int good_id { get; set; }
        public int good_count { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual Users Users { get; set; }
    }
}
