//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreByVlasovAndry.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directories_ToyStore
    {
        public int id_directory { get; set; }
        public int directory_id_user { get; set; }
        public string directory_order_number { get; set; }
    
        public virtual Users_ToyStore Users_ToyStore { get; set; }
    }
}
