//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreByVlasovAndry.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeCategories_ToyStore> AgeCategories_ToyStore { get; set; }
        public virtual DbSet<Categories_ToyStore> Categories_ToyStore { get; set; }
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Countries_ToyStore> Countries_ToyStore { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Directories_ToyStore> Directories_ToyStore { get; set; }
        public virtual DbSet<Edenices> Edenices { get; set; }
        public virtual DbSet<Givers> Givers { get; set; }
        public virtual DbSet<Main> Main { get; set; }
        public virtual DbSet<Makers> Makers { get; set; }
        public virtual DbSet<Manufacturers_ToyStore> Manufacturers_ToyStore { get; set; }
        public virtual DbSet<Names> Names { get; set; }
        public virtual DbSet<Orders_ToyStore> Orders_ToyStore { get; set; }
        public virtual DbSet<Providers_ToyStore> Providers_ToyStore { get; set; }
        public virtual DbSet<Roles_ToyStore> Roles_ToyStore { get; set; }
        public virtual DbSet<Status_ToyStore> Status_ToyStore { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Toys_ToyStore> Toys_ToyStore { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_ToyStore> Users_ToyStore { get; set; }
    }
}
