//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoreByVlasovAndry.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_ToyStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_ToyStore()
        {
            this.Directories_ToyStore = new HashSet<Directories_ToyStore>();
        }
    
        public int id_user { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public int user_id_role { get; set; }
        public string user_name { get; set; }
        public string user_phone { get; set; }
        public string user_mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Directories_ToyStore> Directories_ToyStore { get; set; }
        public virtual Roles_ToyStore Roles_ToyStore { get; set; }
    }
}
